export * from './home/home'
export * from './about/about'
export * from './projects/projects'
export * from './experience/experience'
export * from './socials/socials'
export * from './contact/contact'
export * from './footer/footer'
