export * from './about/about'
export * from './contact/contact'
export * from './footer/footer'
export * from './projects/projects'
export * from './socials/socials'
export * from './navbar/navbar'
export * from './home/home'
